# Generated by Django 5.0.4 on 2024-04-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='описания сервиса')),
                ('des', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Логотип')),
            ],
        ),
    ]
