# Generated by Django 5.0.4 on 2024-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about_alter_servise_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name1',
            field=models.CharField(default=1, max_length=255, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
